export { render } from './internal/render.js';
export type { RenderOptions, RenderHandle, CopyEvent } from './internal/render.js';
export { renderToString } from './internal/renderToString.js';
export type { RenderToStringOptions } from './internal/renderToString.js';
export { useApp } from './hooks/useApp.js';
export { useClick } from './hooks/useClick.js';
export type { AppApi } from './context/appContext.js';
export type { ErrorSource } from './components/ErrorBoundary.js';
export { useTerminalSize, type TerminalSize } from './hooks/useTerminalSize.js';
export { useColorScheme } from './hooks/useColorScheme.js';
export { Box } from './components/base/Box.js';
export { Text } from './components/base/Text.js';
export { Span, type SpanProps } from './components/base/Span.js';
export type { BoxProps, ScrollMetrics, InputRow, EditorOptions, TextRun, WrapContinuation } from '@flowtty/core';
export { inputRows, caretPosition, rowIndexAt } from '@flowtty/core';
// Re-export core types from @flowtty/core so consumers using only @flowtty/react
// have a single import surface for everything they typically need.
export { Buffer } from '@flowtty/core';
export type { Backend, Cell, Style, Key, KeyName, NamedKey, MouseButton, Color, NamedColor, ColorScheme, TerminalColorScheme } from '@flowtty/core';
export { NAMED_KEYS, NAMED_COLORS } from '@flowtty/core';
export type { BorderStyle, BorderChars, GridChars } from '@flowtty/core';
export { DEFAULT_BORDER_STYLE, GRID_CHARS } from '@flowtty/core';
export { useInput } from './hooks/useInput.js';
export type { UseInputOptions } from './hooks/useInput.js';
export { useBackend } from './hooks/useBackend.js';
export { useFullScreenBackend } from './hooks/useFullScreenBackend.js';
export { useRootAbortSignal } from './hooks/useRootAbortSignal.js';
export { useTicker } from './hooks/useTicker.js';
export type { UseTickerOptions } from './hooks/useTicker.js';
export { BackendContext } from './context/backendContext.js';
export { AbortContext } from './context/abortContext.js';
export { Static, type StaticProps } from './components/Static.js';
export type { InputSource, KeySubscriber } from './context/inputContext.js';
export { TextInput } from './components/TextInput.js';
export type { TextInputProps } from './components/TextInput.js';
export { TextArea, type TextAreaProps } from './components/TextArea.js';
export type { TextProps } from './components/base/Text.js';
export type { WrapMode } from '@flowtty/core';
export { Checkbox } from './components/Checkbox.js';
export type { CheckboxProps, CheckboxState, CheckboxFrame } from './components/Checkbox.js';
export { checkboxMarker } from './components/checkboxMarker.js';
export { Select } from './components/Select.js';
export type { SelectProps, SelectSingleProps, SelectMultipleProps, SelectFrame } from './components/Select.js';
export { ListSelect } from './components/ListSelect.js';
export type { SelectItem, ListSelectProps } from './components/ListSelect.js';
export { ListMultiSelect } from './components/ListMultiSelect.js';
export type { ListMultiSelectProps } from './components/ListMultiSelect.js';
export { Confirm } from './components/Confirm.js';
export type { ConfirmProps } from './components/Confirm.js';
export { Form } from './components/Form.js';
export type { FormProps } from './components/Form.js';
export { useField } from './hooks/useField.js';
export type { UseFieldOptions, FieldControl } from './hooks/useField.js';
export type { FormApi, FormFieldRegistration } from './context/formContext.js';
export { DialogHost, type DialogHostProps } from './components/DialogHost.js';
export { useDialog, useDialogHost, useDialogIsTop } from './hooks/useDialog.js';
export type {
  DialogHostApi, DialogResultApi, DialogResult,
} from './context/dialogContext.js';
export { FocusGroup } from './components/FocusGroup.js';
export type { FocusGroupProps } from './components/FocusGroup.js';
export { useFocus } from './hooks/useFocus.js';
export type { UseFocusResult } from './hooks/useFocus.js';
export { Button } from './components/Button.js';
export type { ButtonProps } from './components/Button.js';
export { windowAround } from '@flowtty/core';
export { splitVisualLines, type VisualLine } from '@flowtty/core';
export { charWidth, graphemes, clusterWidth, stringWidth, fitClusters, prevGrapheme, nextGrapheme, setWidthPolicy, widthPolicy, type WidthPolicy } from '@flowtty/core';
export { Title } from './components/Title.js';
export { HRule } from './components/HRule.js';
export { HelpBar } from './components/HelpBar.js';
export { Menu, type MenuItem, type MenuProps } from './components/Menu.js';
export { Spinner, type SpinnerProps, type SpinnerType } from './components/Spinner.js';
export { Shimmer, type ShimmerProps } from './components/Shimmer.js';
export { ProgressBar, type ProgressBarProps } from './components/ProgressBar.js';
export { TaskList, type TaskListProps, type TaskItem, type TaskState } from './components/TaskList.js';
export { Table, type TableProps, type TableColumn, type TableAlign, type TableCellStyle } from './components/Table.js';
export { Link, type LinkProps } from './components/Link.js';
export { ScrollBox, type ScrollBoxProps, type ScrollBoxHandle } from './components/ScrollBox.js';
export { ScrollList, type ScrollListProps } from './components/ScrollList.js';
export { Markdown, type MarkdownProps } from './components/Markdown.js';
export { layoutMarkdown, layoutMarkdownDetailed, type StyledLine, type StyledSpan } from './components/markdown/layout.js';
export type {
  MarkdownOptions, MarkdownLayout, MarkdownCodeBlock, MarkdownCodeFence, MarkdownCodeWrap,
} from './components/markdown/layout.js';
export { highlightMarkdownSource, type SourceLine } from './components/markdown/source.js';
export { parseMarkdown, parseInline } from './components/markdown/parse.js';
export type { MdBlock, MdList, MdListItem, MdAlign, InlineSeg } from './components/markdown/parse.js';
export { HIGHLIGHTED_LANGUAGES, type HighlightedLanguage } from './components/markdown/highlight/index.js';
export type { Point } from '@flowtty/core/host';
